elementary:
 target: DEV
 outputs:
  DEV:
    account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
    database: DBT_PROJECT
    schema: FARGATE_TEST
    user: "{{ env_var('SNOWFLAKE_USERNAME') }}"
    password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
    threads: 4
    type: snowflake
    warehouse: DBT_PROD_WH
